### ISSUE TITLE
Validate the JSON schema file

### ISSUE THREAD

**Issue by alevarn** [Fundamentals-KTH-CSC-2022-P3/gson#1]
We want to validate the JSON schema file to ensure that it has the correct format. Furthermore that the schema file only uses allowed members/properties depending on the `type` of the current node.

Create a `JsonSchemaValidator` class inside the `com.google.gson` package.

Add a `public static` function `validate(JsonElement schemaRoot)` that checks if there is something wrong with the schema file, and if so throws a `JsonSchemaMisformatException` with an error message describing what was wrong.

For now, we will limit our implementation of JSON schema to the following:
- The schema root must be a boolean or an object.
- If the root is an object it can contain the property `"$schema"` (but we don't care about the URI)
-  If the root is an object it can contain the property `"$id"` (but we don't care about the URI)
- Every data structure (can be nested) can specifiy the `"type"` property
- We also must support the following properties: 
  - `"title"`  (but we don't care about the content)
  -  `"description"`  (but we don't care about the content)
  - `"properties"` (only applicable if the `type` is `object`)
  -  `"required"` (only applicable if the `type` is `object`)
  - `"items"` (only applicable if the `type` is `array`)
  - `"minItems"` (only applicable if the `type` is `array`)
  - `"uniqueItems"` (only applicable if the `type` is `array`)
  - "`exclusiveMinimum`" (only applicable if the `type` is `number`)
  - "`minimum`" (only applicable if the `type` is `number`)
  - "`maximum`" (only applicable if the `type` is `number`)
 
Add a few unit-tests for the `JsonSchemaValidator` class.

**Comment by siberov** [comment]
"something wrong with the schema file" means that it does not follow https://json-schema.org/draft/2020-12/json-schema-core.html and https://json-schema.org/draft/2020-12/json-schema-validation.html . We don't have to check that it is valid JSON, necessarily.

One example of something wrong could be that a "properties" field is present, but the value is not an object.
