### ISSUE TITLE
Check if the JSON instance matches with the schema file

### ISSUE THREAD

**Issue by alevarn** [Fundamentals-KTH-CSC-2022-P3/gson#2]
Create a class `JsonSchemaMatcher` that will perform a check to see if an input JSON instance matches with a schema file (note that the schema file also is in JSON).

Create the `JsonSchemaMatcher` class inside the `com.google.gson.schema` package.

The `JsonSchemaMatcher` should have a constructor that takes the schema as input:
- `JsonSchemaMatcher(String schema)`

Create a public method `matches(String jsonInstance)` that checks if the provided JSON instance string matches with the schema file, if not, then throw an exception of type `JsonSchemaMatchingException` with an error message that describes why the JSON instance did not match with the schema file.

For now, we will limit our implementation of JSON schema to the following:
- The schema root must be a boolean or an object.
- If the root is an object it can contain the property `"$schema"` (but we don't care about the URI)
-  If the root is an object it can contain the property `"$id"` (but we don't care about the URI)
- Every data structure (can be nested) can specifiy the `"type"` property
- We also must support the following properties: 
  - `"title"`  (but we don't care about the content)
  -  `"description"`  (but we don't care about the content)
  - `"properties"` (only applicable if the `type` is `object`)
  -  `"required"` (only applicable if the `type` is `object`)
  - `"items"` (only applicable if the `type` is `array`)
  - `"minItems"` (only applicable if the `type` is `array`)
  - `"uniqueItems"` (only applicable if the `type` is `array`)
  - "`exclusiveMinimum`" (only applicable if the `type` is `number`)
  - "`exclusiveMaximum`" (only applicable if the `type` is `number`)
  - "`minimum`" (only applicable if the `type` is `number`)
  - "`maximum`" (only applicable if the `type` is `number`)

Add a few unit-tests for the `JsonSchemaMatcher` class.

**Comment by siberov** [comment]
- [x] ~~TODO: Specify a MVP definition of this~~
